---
:sender: hoge@example.com
:tz: "+09:00"
:tasks:
  newspaper:
    :media:
    - nikkei-free
    - wsj-paid
    :receiver:
    - reader1@kindle.com
    - reader2@kindle.com
    - dropbox:/news
  watch:
    :media:
    - internet-watch
    :receiver:
    - reader1@kindle.com
    - dropbox:/watch
  diary:
    :media:
    - tdiary
    :option:
      tdiary_top: http://sho.tdiary.net/
    :receiver:
    - reader2@kindle.com
:schedule:
  4:
  - newspaper
  17:
  - newspaper
  - watch
  - diary
